#!/usr/bin/env python3
"""Generate the authoritative reproduction-record table of PAPER-n6-872 from
record.tsv, and (optionally) splice it into the LaTeX source.

    python3 gen_record.py                       # print the LaTeX to stdout
    python3 gen_record.py -o record-table.tex   # write it to a file
    python3 gen_record.py --splice PAPER.tex    # rewrite the marked region

The paper carries exactly one reproduction record; it is this table.  Adding a
verification result is a one-line edit of record.tsv followed by --splice.
"""
import argparse
import os
import sys

BEGIN = "% BEGIN GENERATED RECORD TABLE -- generated by src/record/gen_record.py from src/record/record.tsv; do not edit by hand"
END = "% END GENERATED RECORD TABLE"

HEAD = r"""\begingroup
\setlength{\tabcolsep}{3pt}
\scriptsize
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{0.85cm}>{\raggedright\arraybackslash}p{2.57cm}>{\raggedright\arraybackslash}p{2.95cm}>{\raggedright\arraybackslash}p{2.8cm}>{\raggedright\arraybackslash}p{2.2cm}>{\raggedright\arraybackslash}p{2.8cm}@{}}
\caption{\textbf{The reproduction record.}  This table is the sole
authoritative record of what has been verified, by how many
implementations, over what range.  ``Written'' counts \emph{independently
written} implementations (a second derivation of the computation);
``build'' means an independent \emph{build} of one audited source, which
re-executes but does not re-derive.  No reproduction, re-execution or
independence claim is made anywhere else in this paper; where the body
mentions one it is pointing here.}\label{tab:record}\\
\toprule
& artefact / computation & implementations & scope covered & nodes & residual gap\\
\midrule
\endfirsthead
\multicolumn{6}{@{}l}{\emph{Table~\ref{tab:record}, continued}}\\
\toprule
& artefact / computation & implementations & scope covered & nodes & residual gap\\
\midrule
\endhead
\bottomrule
\endlastfoot
"""

FOOT = r"""\end{longtable}
\endgroup
"""


def load(path):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) != 6:
                sys.exit("%s: expected 6 tab-separated fields, got %d in: %s"
                         % (path, len(fields), line[:60]))
            if fields[0] == "id":       # header line
                continue
            rows.append(fields)
    if not rows:
        sys.exit("%s: no data rows" % path)
    return rows


def render(rows):
    body = []
    for rid, what, impl, scope, nodes, gap in rows:
        body.append("(%s) & %s & %s & %s & %s & %s\\\\\n\\addlinespace[2pt]\n"
                    % (rid, what, impl, scope, nodes, gap))
    return HEAD + "".join(body) + FOOT


def splice(texpath, table):
    with open(texpath, encoding="utf-8") as fh:
        src = fh.read()
    i, j = src.find(BEGIN), src.find(END)
    if i < 0 or j < 0:
        sys.exit("%s: markers not found; insert\n%s\n%s\nwhere the table goes."
                 % (texpath, BEGIN, END))
    new = src[:i] + BEGIN + "\n" + table + src[j:]
    with open(texpath, "w", encoding="utf-8") as fh:
        fh.write(new)
    print("spliced %d rows into %s" % (table.count("\\addlinespace"), texpath))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=os.path.join(here, "record.tsv"))
    ap.add_argument("-o", "--out")
    ap.add_argument("--splice", action="append", default=[],
                    help="LaTeX file to rewrite between the record markers "
                         "(may be given more than once)")
    a = ap.parse_args()
    rows = load(a.data)
    table = render(rows)
    for path in a.splice:
        splice(path, table)
    if a.out:
        with open(a.out, "w", encoding="utf-8") as fh:
            fh.write(table)
        print("wrote %s (%d rows)" % (a.out, len(rows)))
    elif not a.splice:
        sys.stdout.write(table)


if __name__ == "__main__":
    main()
